// Shared domain types for NUGGET. Kept dependency-free so both the ingest
// worker and the Next.js frontend can import them.

export type Dex = "uniswap-v3" | "uniswap-v4";

export type EventKind = "swap" | "mint" | "burn";

/**
 * A single normalized pool event, already priced into USD by the adapter.
 * Adapters are responsible for turning chain-specific / DEX-specific event
 * shapes into this one flat shape. The rollup never sees raw chain data.
 */
export interface PoolEvent {
  poolId: string; // lowercased pool address (v3) or poolId (v4)
  dex: Dex;
  kind: EventKind;
  timestamp: number; // unix seconds (UTC)
  amountUsd: number; // swap volume, or |liquidity delta|, in USD
  feeUsd: number; // fees generated by this event (0 for mint/burn)
  priceToken0InToken1?: number; // price at the event, if known
  lpAddress?: string; // for mint/burn, the LP; enables distinct-LP counts
  trader?: string; // for swaps, the sender; powers unique-trader + top-wallet trust signals
}

/** Pool identity/metadata as tracked in the registry. */
export interface PoolMeta {
  id: string;
  dex: Dex;
  token0Symbol: string;
  token1Symbol: string;
  token0?: string;
  token1?: string;
  feeTier?: number;
  tvlUsd?: number; // current TVL snapshot, if the source can provide it
}

/** A finished 5-minute rollup row, ready to upsert into pool_pulse_5m. */
export interface Pulse5m {
  poolId: string;
  bucketStart: string; // ISO timestamp, aligned to the 5m boundary
  feesUsd: number;
  volumeUsd: number;
  liquidityAddUsd: number;
  liquidityRmUsd: number;
  swapCount: number;
  mintCount: number;
  burnCount: number;
  lpCount: number | null;
  uniqueTraders: number | null;
  topWalletPct: number | null; // % of window volume from the single biggest wallet
  priceOpen: number | null;
  priceClose: number | null;
  activeLiquidity: number | null;
}

/**
 * The data source contract. Swap Bitquery for Goldsky (or a raw-RPC adapter)
 * by implementing this one interface — nothing downstream changes.
 */
export interface IngestAdapter {
  readonly name: string;

  /** Top-N currently active pools by 24h volume, for the tracked-pool registry. */
  listTopPools(limit: number): Promise<PoolMeta[]>;

  /**
   * All normalized events for the given pools in [fromTs, toTs).
   * Must be safe to call for a narrow window (one cron tick) or a backfill.
   */
  fetchEvents(
    poolIds: string[],
    fromTs: number,
    toTs: number,
  ): Promise<PoolEvent[]>;

  /**
   * OPTIONAL. Some sources (e.g. GeckoTerminal) already expose pre-aggregated
   * rolling windows, so instead of streaming raw events they hand back finished
   * 5m rows for the current bucket directly — the worker upserts these and skips
   * the event rollup entirely. Adapters that emit events leave this undefined.
   */
  fetchPulseRows?(pools: PoolMeta[], bucketStartIso: string): Promise<Pulse5m[]>;
}
